# Generated by Django 4.2.3 on 2025-11-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(help_text='Primary key identifier', primary_key=True, serialize=False)),
                ('sku', models.TextField(help_text='Stock Keeping Unit - unique identifier', unique=True)),
                ('name', models.TextField(help_text='Product name')),
                ('description', models.TextField(help_text='Product description')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Product status: active or inactive', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-updated_at'],
            },
        ),
    ]
