# Generated by Django 4.2.3 on 2025-11-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(help_text='Primary key identifier', primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='Webhook URL endpoint', max_length=500)),
                ('name', models.CharField(help_text='Webhook name/description', max_length=200)),
                ('event_types', models.JSONField(default=list, help_text="List of event types to trigger this webhook (e.g., ['product.created', 'product.updated'])")),
                ('enabled', models.BooleanField(default=True, help_text='Whether the webhook is enabled')),
                ('secret', models.CharField(blank=True, help_text='Optional secret key for webhook signature verification', max_length=255, null=True)),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Custom headers to include in webhook requests (JSON object)')),
                ('timeout', models.IntegerField(default=30, help_text='Request timeout in seconds')),
                ('retry_count', models.IntegerField(default=3, help_text='Number of retry attempts on failure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, help_text='Last time webhook was triggered', null=True)),
                ('last_response_code', models.IntegerField(blank=True, help_text='Last HTTP response code received', null=True)),
                ('last_response_time', models.FloatField(blank=True, help_text='Last response time in milliseconds', null=True)),
            ],
            options={
                'db_table': 'webhooks',
                'ordering': ['-created_at'],
            },
        ),
    ]
